// Generated by CoffeeScript 1.6.3
(function() {
  document.addEventListener('DOMContentLoaded', function() {
    var startBtn,
      _this = this;
    startBtn = document.getElementById('start');
    console.log('ContentLoaded');
    chrome.storage.local.get('hours', function(result) {
      return new Dropdown(document, 'hours').set(result.hours);
    });
    chrome.storage.local.get('minutes', function(result) {
      return new Dropdown(document, 'minutes').set(result.minutes);
    });
    return startBtn.addEventListener('click', function() {
      var hours, minutes;
      hours = new Dropdown(document, 'hours').getAndStoreResult();
      minutes = new Dropdown(document, 'minutes').getAndStoreResult();
      return chrome.runtime.sendMessage({
        action: 'startTimer',
        hours: hours,
        minutes: minutes
      });
    });
  });

}).call(this);
