// Generated by CoffeeScript 1.6.3
(function() {
  chrome.runtime.onMessage.addListener(function(request, sender, sendResponse) {
    var interval, timer,
      _this = this;
    timer = new Timer(request.hours, request.minutes);
    timer.start();
    return interval = window.setInterval(function() {
      timer.tick();
      if (timer.isExpired()) {
        timer.stop();
        return window.clearInterval(interval);
      }
    }, 60000);
  });

}).call(this);
