// Generated by CoffeeScript 1.6.3
(function() {
  this.Tab = (function() {
    function Tab(id) {
      this.id = id;
    }

    Tab.prototype.close = function(callback) {
      var _this = this;
      return this.getTab(this.id, function() {
        return chrome.tabs.remove(_this.id);
      });
    };

    Tab.prototype.setBadgeText = function(text) {
      var _this = this;
      return this.getTab(this.id, function() {
        return chrome.browserAction.setBadgeText({
          text: text,
          tabId: _this.id
        });
      });
    };

    Tab.prototype.getTab = function(id, callback) {
      return chrome.tabs.get(id, function() {
        if (!chrome.runtime.lastError) {
          return callback();
        }
      });
    };

    return Tab;

  })();

}).call(this);
